<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CorporateSite.Application\CorporateSite.Application.csproj" />
    <ProjectReference Include="..\DataProviderInfrastructure\DataProviderInfrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.Core" Version="8.0.0" />
    <PackageReference Include="Ganss.Xss" Version="2.1.4" />
  </ItemGroup>
</Project>
